movie:
  movie_id: tt1591095
  title: Insidious
  fps: null

files:
  annotation_file: tt1591095.json
  meta_file: tt1591095.json
  script_file: tt1591095.script
  subtitle_file: tt1591095.srt
  video_file: tt1591095.mp4

character_map:

  CHAR_A:
    name: null
    movienet_pid: null
    script_aliases: null

  CHAR_B:
    name: null
    movienet_pid: null
    script_aliases: null
